apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  storageClassName: mehmetemin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi