apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mehmetemin
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mehmetemin
  local:
    path: /mnt/volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker